#!/usr/bin/env python3

# buildbot test

from libhowdy import lib1

def main():
	print('howdy')
	ret = lib1.testme()
	print(f'lib1.testme() returned {ret}')

	input("Press enter to close")

if __name__ == '__main__':
	main()
